### ISSUE TITLE
Download link AppEngine is over quota

### ISSUE THREAD

**Issue by mapmeld** [google-research-datasets/discofuse#1]
I found this dataset through [the FELIX tutorial](https://github.com/google-research/google-research/blob/master/felix/run_discofuse_experiment.sh) , unfortunately the links both return errors of being over quota.

```
<Error>
<Code>InsufficientQuota</Code>
<Message>The App Engine application does not have enough quota.</Message>
<Details>App e~discofuse does not have enough quota</Details>
</Error>
```

**Comment by ekQ** [comment]
I tested accessing the following link from README https://storage.googleapis.com/discofuse.appspot.com/discofuse_v1_wikipedia.zip and was able to download the dataset. Could you try again to see if the problem persists for you?

**Comment by mapmeld** [comment]
works for me
